/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AccessBlockedRouteImport } from './routes/access-blocked'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedActionsRouteImport } from './routes/_authenticated/actions'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedOrganizationsRouteImport } from './routes/_authenticated/organizations'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedVesselsRouteImport } from './routes/_authenticated/vessels'
import { Route as AuthenticatedActionsIndexRouteImport } from './routes/_authenticated/actions.index'
import { Route as AuthenticatedActionsNewRouteImport } from './routes/_authenticated/actions.new'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients.index'
import { Route as AuthenticatedClientsNewRouteImport } from './routes/_authenticated/clients.new'
import { Route as AuthenticatedDevObservabilityRouteImport } from './routes/_authenticated/dev.observability'
import { Route as AuthenticatedOrganizationsNewRouteImport } from './routes/_authenticated/organizations.new'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users.index'
import { Route as AuthenticatedUsersNewRouteImport } from './routes/_authenticated/users.new'
import { Route as AuthenticatedVesselsIndexRouteImport } from './routes/_authenticated/vessels.index'
import { Route as AuthenticatedVesselsNewRouteImport } from './routes/_authenticated/vessels.new'
import { Route as AuthenticatedActionsActionIdIndexRouteImport } from './routes/_authenticated/actions.$actionId.index'
import { Route as AuthenticatedActionsActionIdEditRouteImport } from './routes/_authenticated/actions.$actionId.edit'
import { Route as AuthenticatedClientsClientIdEditRouteImport } from './routes/_authenticated/clients.$clientId.edit'
import { Route as AuthenticatedVesselsVesselIdEditRouteImport } from './routes/_authenticated/vessels.$vesselId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessBlockedRoute = AccessBlockedRouteImport.update({
  id: '/access-blocked',
  path: '/access-blocked',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedActionsRoute = AuthenticatedActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrganizationsRoute =
  AuthenticatedOrganizationsRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVesselsRoute = AuthenticatedVesselsRouteImport.update({
  id: '/vessels',
  path: '/vessels',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActionsIndexRoute =
  AuthenticatedActionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedActionsRoute,
  } as any)
const AuthenticatedActionsNewRoute = AuthenticatedActionsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedActionsRoute,
} as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClientsRoute,
  } as any)
const AuthenticatedClientsNewRoute = AuthenticatedClientsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedClientsRoute,
} as any)
const AuthenticatedDevObservabilityRoute =
  AuthenticatedDevObservabilityRouteImport.update({
    id: '/dev/observability',
    path: '/dev/observability',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrganizationsNewRoute =
  AuthenticatedOrganizationsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedOrganizationsRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedUsersRoute,
} as any)
const AuthenticatedUsersNewRoute = AuthenticatedUsersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedUsersRoute,
} as any)
const AuthenticatedVesselsIndexRoute =
  AuthenticatedVesselsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedVesselsRoute,
  } as any)
const AuthenticatedVesselsNewRoute = AuthenticatedVesselsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedVesselsRoute,
} as any)
const AuthenticatedActionsActionIdIndexRoute =
  AuthenticatedActionsActionIdIndexRouteImport.update({
    id: '/$actionId/',
    path: '/$actionId/',
    getParentRoute: () => AuthenticatedActionsRoute,
  } as any)
const AuthenticatedActionsActionIdEditRoute =
  AuthenticatedActionsActionIdEditRouteImport.update({
    id: '/$actionId/edit',
    path: '/$actionId/edit',
    getParentRoute: () => AuthenticatedActionsRoute,
  } as any)
const AuthenticatedClientsClientIdEditRoute =
  AuthenticatedClientsClientIdEditRouteImport.update({
    id: '/$clientId/edit',
    path: '/$clientId/edit',
    getParentRoute: () => AuthenticatedClientsRoute,
  } as any)
const AuthenticatedVesselsVesselIdEditRoute =
  AuthenticatedVesselsVesselIdEditRouteImport.update({
    id: '/$vesselId/edit',
    path: '/$vesselId/edit',
    getParentRoute: () => AuthenticatedVesselsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-blocked': typeof AccessBlockedRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/actions': typeof AuthenticatedActionsRouteWithChildren
  '/app': typeof AuthenticatedAppRoute
  '/clients': typeof AuthenticatedClientsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/organizations': typeof AuthenticatedOrganizationsRouteWithChildren
  '/reports': typeof AuthenticatedReportsRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/users': typeof AuthenticatedUsersRouteWithChildren
  '/vessels': typeof AuthenticatedVesselsRouteWithChildren
  '/actions/new': typeof AuthenticatedActionsNewRoute
  '/clients/new': typeof AuthenticatedClientsNewRoute
  '/dev/observability': typeof AuthenticatedDevObservabilityRoute
  '/organizations/new': typeof AuthenticatedOrganizationsNewRoute
  '/users/new': typeof AuthenticatedUsersNewRoute
  '/vessels/new': typeof AuthenticatedVesselsNewRoute
  '/actions/': typeof AuthenticatedActionsIndexRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/vessels/': typeof AuthenticatedVesselsIndexRoute
  '/actions/$actionId/edit': typeof AuthenticatedActionsActionIdEditRoute
  '/clients/$clientId/edit': typeof AuthenticatedClientsClientIdEditRoute
  '/vessels/$vesselId/edit': typeof AuthenticatedVesselsVesselIdEditRoute
  '/actions/$actionId/': typeof AuthenticatedActionsActionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-blocked': typeof AccessBlockedRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app': typeof AuthenticatedAppRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/organizations': typeof AuthenticatedOrganizationsRouteWithChildren
  '/reports': typeof AuthenticatedReportsRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/actions/new': typeof AuthenticatedActionsNewRoute
  '/clients/new': typeof AuthenticatedClientsNewRoute
  '/dev/observability': typeof AuthenticatedDevObservabilityRoute
  '/organizations/new': typeof AuthenticatedOrganizationsNewRoute
  '/users/new': typeof AuthenticatedUsersNewRoute
  '/vessels/new': typeof AuthenticatedVesselsNewRoute
  '/actions': typeof AuthenticatedActionsIndexRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/vessels': typeof AuthenticatedVesselsIndexRoute
  '/actions/$actionId/edit': typeof AuthenticatedActionsActionIdEditRoute
  '/clients/$clientId/edit': typeof AuthenticatedClientsClientIdEditRoute
  '/vessels/$vesselId/edit': typeof AuthenticatedVesselsVesselIdEditRoute
  '/actions/$actionId': typeof AuthenticatedActionsActionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/access-blocked': typeof AccessBlockedRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/actions': typeof AuthenticatedActionsRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/organizations': typeof AuthenticatedOrganizationsRouteWithChildren
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRouteWithChildren
  '/_authenticated/vessels': typeof AuthenticatedVesselsRouteWithChildren
  '/_authenticated/actions/new': typeof AuthenticatedActionsNewRoute
  '/_authenticated/clients/new': typeof AuthenticatedClientsNewRoute
  '/_authenticated/dev/observability': typeof AuthenticatedDevObservabilityRoute
  '/_authenticated/organizations/new': typeof AuthenticatedOrganizationsNewRoute
  '/_authenticated/users/new': typeof AuthenticatedUsersNewRoute
  '/_authenticated/vessels/new': typeof AuthenticatedVesselsNewRoute
  '/_authenticated/actions/': typeof AuthenticatedActionsIndexRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/vessels/': typeof AuthenticatedVesselsIndexRoute
  '/_authenticated/actions/$actionId/edit': typeof AuthenticatedActionsActionIdEditRoute
  '/_authenticated/clients/$clientId/edit': typeof AuthenticatedClientsClientIdEditRoute
  '/_authenticated/vessels/$vesselId/edit': typeof AuthenticatedVesselsVesselIdEditRoute
  '/_authenticated/actions/$actionId/': typeof AuthenticatedActionsActionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-blocked'
    | '/auth'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/actions'
    | '/app'
    | '/clients'
    | '/dashboard'
    | '/notifications'
    | '/organizations'
    | '/reports'
    | '/search'
    | '/settings'
    | '/users'
    | '/vessels'
    | '/actions/new'
    | '/clients/new'
    | '/dev/observability'
    | '/organizations/new'
    | '/users/new'
    | '/vessels/new'
    | '/actions/'
    | '/clients/'
    | '/users/'
    | '/vessels/'
    | '/actions/$actionId/edit'
    | '/clients/$clientId/edit'
    | '/vessels/$vesselId/edit'
    | '/actions/$actionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-blocked'
    | '/auth'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/app'
    | '/dashboard'
    | '/notifications'
    | '/organizations'
    | '/reports'
    | '/search'
    | '/settings'
    | '/actions/new'
    | '/clients/new'
    | '/dev/observability'
    | '/organizations/new'
    | '/users/new'
    | '/vessels/new'
    | '/actions'
    | '/clients'
    | '/users'
    | '/vessels'
    | '/actions/$actionId/edit'
    | '/clients/$clientId/edit'
    | '/vessels/$vesselId/edit'
    | '/actions/$actionId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/access-blocked'
    | '/auth'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_authenticated/actions'
    | '/_authenticated/app'
    | '/_authenticated/clients'
    | '/_authenticated/dashboard'
    | '/_authenticated/notifications'
    | '/_authenticated/organizations'
    | '/_authenticated/reports'
    | '/_authenticated/search'
    | '/_authenticated/settings'
    | '/_authenticated/users'
    | '/_authenticated/vessels'
    | '/_authenticated/actions/new'
    | '/_authenticated/clients/new'
    | '/_authenticated/dev/observability'
    | '/_authenticated/organizations/new'
    | '/_authenticated/users/new'
    | '/_authenticated/vessels/new'
    | '/_authenticated/actions/'
    | '/_authenticated/clients/'
    | '/_authenticated/users/'
    | '/_authenticated/vessels/'
    | '/_authenticated/actions/$actionId/edit'
    | '/_authenticated/clients/$clientId/edit'
    | '/_authenticated/vessels/$vesselId/edit'
    | '/_authenticated/actions/$actionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AccessBlockedRoute: typeof AccessBlockedRoute
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-blocked': {
      id: '/access-blocked'
      path: '/access-blocked'
      fullPath: '/access-blocked'
      preLoaderRoute: typeof AccessBlockedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/actions': {
      id: '/_authenticated/actions'
      path: '/actions'
      fullPath: '/actions'
      preLoaderRoute: typeof AuthenticatedActionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organizations': {
      id: '/_authenticated/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof AuthenticatedOrganizationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vessels': {
      id: '/_authenticated/vessels'
      path: '/vessels'
      fullPath: '/vessels'
      preLoaderRoute: typeof AuthenticatedVesselsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/actions/': {
      id: '/_authenticated/actions/'
      path: '/'
      fullPath: '/actions/'
      preLoaderRoute: typeof AuthenticatedActionsIndexRouteImport
      parentRoute: typeof AuthenticatedActionsRoute
    }
    '/_authenticated/actions/new': {
      id: '/_authenticated/actions/new'
      path: '/new'
      fullPath: '/actions/new'
      preLoaderRoute: typeof AuthenticatedActionsNewRouteImport
      parentRoute: typeof AuthenticatedActionsRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedClientsRoute
    }
    '/_authenticated/clients/new': {
      id: '/_authenticated/clients/new'
      path: '/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof AuthenticatedClientsNewRouteImport
      parentRoute: typeof AuthenticatedClientsRoute
    }
    '/_authenticated/dev/observability': {
      id: '/_authenticated/dev/observability'
      path: '/dev/observability'
      fullPath: '/dev/observability'
      preLoaderRoute: typeof AuthenticatedDevObservabilityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organizations/new': {
      id: '/_authenticated/organizations/new'
      path: '/new'
      fullPath: '/organizations/new'
      preLoaderRoute: typeof AuthenticatedOrganizationsNewRouteImport
      parentRoute: typeof AuthenticatedOrganizationsRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedUsersRoute
    }
    '/_authenticated/users/new': {
      id: '/_authenticated/users/new'
      path: '/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof AuthenticatedUsersNewRouteImport
      parentRoute: typeof AuthenticatedUsersRoute
    }
    '/_authenticated/vessels/': {
      id: '/_authenticated/vessels/'
      path: '/'
      fullPath: '/vessels/'
      preLoaderRoute: typeof AuthenticatedVesselsIndexRouteImport
      parentRoute: typeof AuthenticatedVesselsRoute
    }
    '/_authenticated/vessels/new': {
      id: '/_authenticated/vessels/new'
      path: '/new'
      fullPath: '/vessels/new'
      preLoaderRoute: typeof AuthenticatedVesselsNewRouteImport
      parentRoute: typeof AuthenticatedVesselsRoute
    }
    '/_authenticated/actions/$actionId/': {
      id: '/_authenticated/actions/$actionId/'
      path: '/$actionId'
      fullPath: '/actions/$actionId/'
      preLoaderRoute: typeof AuthenticatedActionsActionIdIndexRouteImport
      parentRoute: typeof AuthenticatedActionsRoute
    }
    '/_authenticated/actions/$actionId/edit': {
      id: '/_authenticated/actions/$actionId/edit'
      path: '/$actionId/edit'
      fullPath: '/actions/$actionId/edit'
      preLoaderRoute: typeof AuthenticatedActionsActionIdEditRouteImport
      parentRoute: typeof AuthenticatedActionsRoute
    }
    '/_authenticated/clients/$clientId/edit': {
      id: '/_authenticated/clients/$clientId/edit'
      path: '/$clientId/edit'
      fullPath: '/clients/$clientId/edit'
      preLoaderRoute: typeof AuthenticatedClientsClientIdEditRouteImport
      parentRoute: typeof AuthenticatedClientsRoute
    }
    '/_authenticated/vessels/$vesselId/edit': {
      id: '/_authenticated/vessels/$vesselId/edit'
      path: '/$vesselId/edit'
      fullPath: '/vessels/$vesselId/edit'
      preLoaderRoute: typeof AuthenticatedVesselsVesselIdEditRouteImport
      parentRoute: typeof AuthenticatedVesselsRoute
    }
  }
}

interface AuthenticatedActionsRouteChildren {
  AuthenticatedActionsNewRoute: typeof AuthenticatedActionsNewRoute
  AuthenticatedActionsIndexRoute: typeof AuthenticatedActionsIndexRoute
  AuthenticatedActionsActionIdEditRoute: typeof AuthenticatedActionsActionIdEditRoute
  AuthenticatedActionsActionIdIndexRoute: typeof AuthenticatedActionsActionIdIndexRoute
}

const AuthenticatedActionsRouteChildren: AuthenticatedActionsRouteChildren = {
  AuthenticatedActionsNewRoute: AuthenticatedActionsNewRoute,
  AuthenticatedActionsIndexRoute: AuthenticatedActionsIndexRoute,
  AuthenticatedActionsActionIdEditRoute: AuthenticatedActionsActionIdEditRoute,
  AuthenticatedActionsActionIdIndexRoute:
    AuthenticatedActionsActionIdIndexRoute,
}

const AuthenticatedActionsRouteWithChildren =
  AuthenticatedActionsRoute._addFileChildren(AuthenticatedActionsRouteChildren)

interface AuthenticatedClientsRouteChildren {
  AuthenticatedClientsNewRoute: typeof AuthenticatedClientsNewRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
  AuthenticatedClientsClientIdEditRoute: typeof AuthenticatedClientsClientIdEditRoute
}

const AuthenticatedClientsRouteChildren: AuthenticatedClientsRouteChildren = {
  AuthenticatedClientsNewRoute: AuthenticatedClientsNewRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
  AuthenticatedClientsClientIdEditRoute: AuthenticatedClientsClientIdEditRoute,
}

const AuthenticatedClientsRouteWithChildren =
  AuthenticatedClientsRoute._addFileChildren(AuthenticatedClientsRouteChildren)

interface AuthenticatedOrganizationsRouteChildren {
  AuthenticatedOrganizationsNewRoute: typeof AuthenticatedOrganizationsNewRoute
}

const AuthenticatedOrganizationsRouteChildren: AuthenticatedOrganizationsRouteChildren =
  {
    AuthenticatedOrganizationsNewRoute: AuthenticatedOrganizationsNewRoute,
  }

const AuthenticatedOrganizationsRouteWithChildren =
  AuthenticatedOrganizationsRoute._addFileChildren(
    AuthenticatedOrganizationsRouteChildren,
  )

interface AuthenticatedUsersRouteChildren {
  AuthenticatedUsersNewRoute: typeof AuthenticatedUsersNewRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedUsersRouteChildren: AuthenticatedUsersRouteChildren = {
  AuthenticatedUsersNewRoute: AuthenticatedUsersNewRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedUsersRouteWithChildren =
  AuthenticatedUsersRoute._addFileChildren(AuthenticatedUsersRouteChildren)

interface AuthenticatedVesselsRouteChildren {
  AuthenticatedVesselsNewRoute: typeof AuthenticatedVesselsNewRoute
  AuthenticatedVesselsIndexRoute: typeof AuthenticatedVesselsIndexRoute
  AuthenticatedVesselsVesselIdEditRoute: typeof AuthenticatedVesselsVesselIdEditRoute
}

const AuthenticatedVesselsRouteChildren: AuthenticatedVesselsRouteChildren = {
  AuthenticatedVesselsNewRoute: AuthenticatedVesselsNewRoute,
  AuthenticatedVesselsIndexRoute: AuthenticatedVesselsIndexRoute,
  AuthenticatedVesselsVesselIdEditRoute: AuthenticatedVesselsVesselIdEditRoute,
}

const AuthenticatedVesselsRouteWithChildren =
  AuthenticatedVesselsRoute._addFileChildren(AuthenticatedVesselsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActionsRoute: typeof AuthenticatedActionsRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOrganizationsRoute: typeof AuthenticatedOrganizationsRouteWithChildren
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRouteWithChildren
  AuthenticatedVesselsRoute: typeof AuthenticatedVesselsRouteWithChildren
  AuthenticatedDevObservabilityRoute: typeof AuthenticatedDevObservabilityRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActionsRoute: AuthenticatedActionsRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOrganizationsRoute: AuthenticatedOrganizationsRouteWithChildren,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRouteWithChildren,
  AuthenticatedVesselsRoute: AuthenticatedVesselsRouteWithChildren,
  AuthenticatedDevObservabilityRoute: AuthenticatedDevObservabilityRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AccessBlockedRoute: AccessBlockedRoute,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
